mov r1, r2
mov r1 ; MISSING_ARGS
add #5, r3
add #5 ; MISSING_ARGS
LABEL1: mov r1, r2
1LABEL: mov r1, r2 ; NAME_DOESNT_START_WITH_LETTER
LABEL_TOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO_LONG: mov r1, r2 ; NAME_TOO_LONG
.extern EXTERNAL_LABEL
.extern 1EXTERNAL_LABEL ; NAME_DOESNT_START_WITH_LETTER
.string "Hello, World!"
.string Hello, World! ; MISSING_QUOTE
.data 5, 10, 15
.data 5, , 15 ; EXTRA_COMMA
.data ; MISSING_ARGS
stop
stop EXTRA_OPERAND ; EXTRA_TEXT_AFTER_STRING
